k3s_token = ENV.fetch("K3S_TOKEN", "")
k3s_server_ip = ENV.fetch("K3S_SERVER_IP", "192.168.56.110")
k3s_worker_ip = ENV.fetch("K3S_WORKER_IP", "192.168.56.111")
k3s_channel = ENV.fetch("K3S_CHANNEL", "stable")
scripts_dir = File.join(__dir__, "scripts")

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-12"

  config.vm.define "amontignS" do |server|
    server.vm.hostname = "amontignS"
    server.vm.network "private_network", ip: k3s_server_ip, auto_config: false

    server.vm.provider "vmware_desktop" do |vmware|
      vmware.cpus = 2
      vmware.memory = 2048
      vmware.gui = false
    end

    server.vm.provision "shell",
      path: File.join(scripts_dir, "server.sh"),
      privileged: true,
      env: {
        "K3S_TOKEN" => k3s_token,
        "K3S_SERVER_IP" => k3s_server_ip,
        "K3S_CHANNEL" => k3s_channel,
      }
  end

  config.vm.define "amontignSW" do |worker|
    worker.vm.hostname = "amontignSW"
    worker.vm.network "private_network", ip: k3s_worker_ip, auto_config: false

    worker.vm.provider "vmware_desktop" do |vmware|
      vmware.cpus = 1
      vmware.memory = 1024
      vmware.gui = false
    end

    worker.vm.provision "shell",
      path: File.join(scripts_dir, "worker.sh"),
      privileged: true,
      env: {
        "K3S_SERVER_IP" => k3s_server_ip,
        "K3S_WORKER_IP" => k3s_worker_ip,
        "K3S_CHANNEL" => k3s_channel,
      }
  end
end
